### ISSUE TITLE
Make Blog Post Display Wider

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-website-v1#59]
I think that the default width for the blog posts is too narrow.

I suggest that we change it from `65ch` to something like `105ch`.

@matfantinel What do you think?

https://github.com/torrust/torrust-website/blob/16696369027c31f62d04ae473c8c0c94187a844b/src/routes/(blog-article)/%2Blayout.svelte#L128

**Comment by matfantinel** [comment]
It might come down to personal preference, but the reason I chose 65ch is because there are studies that indicate that lines that are too long or too short might slow down reading - [this link](https://graphicdesign.stackexchange.com/questions/13724/recommended-column-width-for-text-reading-digital-vs-printed) explains it a bit.

Of course this is not absolute and varies by font, design and personal taste. I'd just say to pay attention to how images look if you change it to 105ch! They might get too big depending on their aspect ratio

**Comment by da2ce7** [comment]
The consideration is that there is lots of code blocks and other information embedded into the blog, and these types of information have an advantage where there is extra space. (I think that code is generally most readable at around 130 characters)... because it is imporant to be able to see an entire function in it's context.

However for a blog, of course it should have a less-wide width. - But a technical blog can have a wider width than maybe a social one?

**Comment by matfantinel** [comment]
@da2ce7 that makes sense! On my personal blog there's usually more text than code so 65ch makes sense, but I had a look at your posts and the code blocks do indeed feel constrained.

I played around a bit and actually found a bug in my template - I had intended it to be possible to add some elements with the `full-bleed` class in blog posts, that would take up the full screen width instead of being constrained to the 65ch, but that's not working currently. I'm working on fixing that in the template itself so it can be pulled once that's merged. That way you can have things show up like in the screenshot below.

I'll add it to the CodeBlock so you can pass the prop fullBleed like `<CodeBlock lang="markdown" fullBleed>`

![Arc 2023-07-31 at 18 58 37](https://github.com/torrust/torrust-website/assets/24247035/1b02e30b-3e62-4a88-87cb-16058b44a45a)

**Comment by matfantinel** [comment]
@da2ce7 this is the PR for that feature: https://github.com/matfantinel/sveltekit-static-blog-template/pull/3

The changes can be easily copy-pasted if you want to bring those over.

**Comment by josecelano** [comment]
I think this was closed by https://github.com/torrust/torrust-website/pull/64
